version: '3'

services:
  php:
    build:
      context: php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    container_name: codingame_php
    working_dir: /home/star/codingame
    user: ${USER_ID}
    volumes:
      - ${PATH_DOMAIN}:/home/star/codingame
    environment:
      PHP_IDE_CONFIG: "serverName=test-app"
