# behat.yml
default:
  autoload:
    '': '../codingame'
  suites:
   chuck_norris_feature:
      paths: [ ./tests/Functional/Features/Easy/chuck_norris.feature ]
      contexts: [ CodinGame\Tests\Functional\Features\Bootstrap\Easy\ChuckNorrisContext ]

   power_of_thor_feature:
     paths: [ ./tests/Functional/Features/Easy/power_of_thor.feature ]
     contexts: [ CodinGame\Tests\Functional\Features\Bootstrap\Easy\PowerOfThorContext ]

   art_ascii_feature:
     paths: [ ./tests/Functional/Features/Easy/art_ascii.feature ]
     contexts: [ CodinGame\Tests\Functional\Features\Bootstrap\Easy\ArtASCIIContext ]

   defibrillator_feature:
     paths: [ ./tests/Functional/Features/Easy/defibrillator.feature ]
     contexts: [ CodinGame\Tests\Functional\Features\Bootstrap\Easy\DefibrillatorContext ]

   war_feature:
     paths: [ ./tests/Functional/Features/Medium/war.feature ]
     contexts: [ CodinGame\Tests\Functional\Features\Bootstrap\Medium\WarContext ]

   phone_numbers_feature:
     paths: [ ./tests/Functional/Features/Medium/phone_numbers.feature ]
     contexts: [ CodinGame\Tests\Functional\Features\Bootstrap\Medium\PhoneNumbersContext ]
