# behat.yml
default:
  autoload:
    '': '../codingame'
  suites:
   chuck_norris_feature:
      paths: [ ./tests/Functional/features/chuck_norris.feature ]
      contexts: [ CodinGame\Tests\Functional\Features\Bootstrap\ChuckNorrisContext ]

   power_of_thor_feature:
     paths: [ ./tests/Functional/features/power_of_thor.feature ]
     contexts: [ CodinGame\Tests\Functional\Features\Bootstrap\PowerOfThorContext ]
